/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: d7097763c80377210155859451740427)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	OPENAI_MODEL: "gpt-5.6";
	GITHUB_API_BASE: "https://api.github.com";
	OPENAI_API_KEY: string;
	GITHUB_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OPENAI_MODEL" | "GITHUB_API_BASE" | "OPENAI_API_KEY" | "GITHUB_TOKEN">> {}
}
